name: Windows

on: [push, pull_request]

jobs:
  build-debug-19-x86:
    runs-on: windows-latest
    name: Debug VS2019, x86, Vulkan 1.0

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Debug -DFG_CI_BUILD=ON -DFG_VULKAN_VERSION=100 -DFG_ENABLE_MEMLEAK_CHECKS=ON ..

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Debug --verbose
      
     
  build-release-19-x86:
    runs-on: windows-latest
    name: Release VS2019, x86, Vulkan 1.1

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release  -DFG_CI_BUILD=ON -DFG_VULKAN_VERSION=110 ..

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Release --verbose


  build-debug-19-x64:
    runs-on: windows-latest
    name: Debug VS2019, x64, Vulkan 1.2

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Debug -DFG_CI_BUILD=ON -DFG_VULKAN_VERSION=120 -DFG_ENABLE_MEMLEAK_CHECKS=ON ..

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Debug --verbose
      
     
  build-release-19-x64:
    runs-on: windows-latest
    name: Release VS2019, x64, Vulkan 1.1

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release  -DFG_CI_BUILD=ON -DFG_VULKAN_VERSION=110 ..

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Release --verbose
      
#    - uses: actions/upload-artifact@v2
#      with:
#        name: ${{ github.job }}
#        path: ${{runner.workspace}}/build/bin/Release/*.exe
#        retention-days: 14
